name: small-app-backend
services:
  db:
    build: .
    image: ${IMAGE}
    container_name: ${CONTAINER}
    env_file:
      - ".env"
    restart: "${DOCKER_RESTART_POLICY:-no}"
    deploy:
      resources:
        limits:
          cpus: "${DOCKER_WEB_CPUS:-0}"
          memory: "${DOCKER_WEB_MEMORY:-0}"
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:5432}:${PORT:-5432}"
volumes:
  pgdata:
