---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "small-app-lb-service"
  namespace: "default"
  labels:
    app: "small-app-3"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "small-app-3"
  type: "LoadBalancer"
  loadBalancerIP: "34.66.198.165"
